global:
  scrape_interval: 15s # 全局抓取间隔

scrape_configs:
  # Prometheus 自身的监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # 监控 ETCD 的状态
  - job_name: 'etcd'
    static_configs:
      - targets: ['etcd:2379']

  # 监控 Redis 的状态
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # 监控 Kafka 的状态
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka_broker:9092']

  # 监控 MySQL 的状态
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']

  # 监控 GinTalk 服务的状态
  - job_name: 'gin-talk'
    static_configs:
      - targets: ['gin-talk:8080']
