port: 8080
host: 127.0.0.1
timeout: 10 # 服务超时时间，单位秒
password_secret: "123456"

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  db: GinTalk
  logger:
    loglevel: 1        # 日志级别：1 - 不输出日志，2 - 只输出错误日志，3 - 输出警告和错误日志，4 - 输出所有日志
    slowThreshold: 100 # 慢查询阈值，单位毫秒
    ignoreRecordNotFoundError: true # 忽略记录未找到错误
    colorful: true     # 是否彩色输出
    parameterizedQueries: true # 是否参数化查询

redis:
  host: 127.0.0.1
  port: 6379
  db: 0

logger:
  level: "warn"       # 日志级别：debug, info, warn, error, dpanic, panic, fatal
  format: "json"      # 输出格式：console 或 json
  outputPaths:        # 日志输出路径，可以是多个
    - "stdout"        # 输出到标准输出
    - "./logs/app.log" # 输出到文件
  errorOutputPaths:
    - "stderr"        # 错误日志输出路径
    - "./logs/error.log" # 错误日志输出到文件
  maxSize: 100        # 单个日志文件的最大大小 (MB)
  maxBackups: 7       # 保留的旧日志文件个数
  maxAge: 30          # 日志文件保留天数
  compress: true      # 是否压缩旧的日志文件